[package]
name = "instantcoffee"
version = "0.1.0"
authors = ["***Realname*** ***Lastname*** <***redacted.email@redacted.nope***>"]
edition = "2018"

[dependencies]
failure = "~0.1.5"

[dependencies.coffeegrains]
path = "../coffeegrains"
